spring:
  application:
    name: user-service
  data:
    mongodb:
#      uri: mongodb://localhost:27017/userdb   u8a3Ua5EqWBzl2iL
      uri: mongodb+srv://atuluttam_db_user:jKOH6ixF3D9fAA5U@user-db.lgobyp8.mongodb.net/?retryWrites=true&w=majority&appName=user-db
      database: userdb
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb?currentSchema=public&stringtype=unspecified&options=-c%20TimeZone=Asia/Kolkata
#    username: root
#    password: root
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        jdbc:
#          time_zone: Asia/Kolkata
#    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8082

