version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
#      POSTGRES_DB: ecomdb
      TZ: Asia/Kolkata
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:














#version: "3.9"
#
#services:
#  postgres:
#    container_name: postgres_container
#    image: postgres:14
#    restart: unless-stopped
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: root
#      PGDATA: /data/postgres
#      TZ: Asia/Kolkata
#    volumes:
#      - postgres:/data/postgres
#    networks:
#      - postgres
#
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin_container
#    restart: unless-stopped
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - postgres
#    depends_on:
#      - postgres
#
#networks:
#  postgres:
#    driver: bridge
#
#volumes:
#  postgres:
#  pgadmin:
