spring:
  application:
    name: order-service
#  datasource:
#    url: jdbc:h2:mem:test   # In-memory DB, replace with jdbc:h2:file:./data/ecomdb for file-based
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: abc
#
#  jpa:
#    hibernate:
#      ddl-auto: update       # create | create-drop | validate | update
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#
#  h2:
#    console:
#      enabled: true          # Enable H2 console
#      path: /h2-console      # Access at http://localhost:8082/h2-console
  datasource:
    url: jdbc:postgresql://localhost:5432/order?currentSchema=public&stringtype=unspecified&options=-c%20TimeZone=Asia/Kolkata
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083
