spring:
  application:
    name: M2_Ecom

  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb?currentSchema=public&stringtype=unspecified&options=-c%20TimeZone=Asia/Kolkata
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

# ===========================
# Optional: H2 Configuration (commented out)
# ===========================
# spring:
#   datasource:
#     url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
#     driver-class-name: org.h2.Driver
#     username: sa
#     password:
#
#   h2:
#     console:
#       enabled: true
#       path: /h2-console
#
#   jpa:
#     database: H2
#     show-sql: true
#     hibernate:
#       ddl-auto: update
#     database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: MyApp
    description: EComm App
    version: 1.0.0

server:
  shutdown: graceful
